worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /var/log/nginx/access.log;
    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name _;
        root /var/www/mc-task;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /mc_task/ {
            alias /var/www/mc-task/;
            try_files $uri $uri/;
        }

        location /portfolio/ {
            alias /var/www/portfolio/;
            try_files $uri $uri/;
        }

        location /sleep/ {
            alias /var/www/sleep-aid/;
            try_files $uri $uri/;
        }

        location /chat/ {
            alias /var/www/art-chat/;
            try_files $uri $uri/;
        }
    }
}
