server {
    listen 80;
    server_name _;
    root /var/www/mc-task;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /mc_task {
        alias /var/www/mc-task;
        index index.html;
    }

    location /portfolio {
        alias /var/www/portfolio;
        index index.html;
    }

    location /sleep {
        alias /var/www/sleep-aid;
        index index.html;
    }

    location /chat {
        alias /var/www/art-chat;
        index index.html;
    }
}
